# Generated by Django 3.1.5 on 2021-01-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210119_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='published_at',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_max',
            new_name='salary_from',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_min',
            new_name='salary_to',
        ),
    ]
