# Generated by Django 3.1.5 on 2021-01-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20210119_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_from',
            new_name='salary_max',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='salary_to',
            new_name='salary_min',
        ),
    ]
